[server]
headless = true
address = "0.0.0.0"
port = 5000
maxUploadSize = 5000
maxMessageSize = 1000
enableXsrfProtection = false
enableCORS = false

[theme]
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
